import type { NpcCostumeId, NpcCostumePalette, NpcTypeDef } from './types'

/** Fallback palettes from docs/research/nature_people.md — stylized HEX. */
export const FALLBACK_COSTUMES: Record<NpcCostumeId, NpcCostumePalette> = {
  npc_vua: {
    id: 'npc_vua',
    primary: '#E8B923',
    secondary: '#1A4B8C',
    accent: '#D4AF37',
    skin: '#F5F5F0',
    hat: '#1A4B8C',
  },
  npc_quan_van: {
    id: 'npc_quan_van',
    primary: '#5B2C6F',
    secondary: '#2E6B4F',
    accent: '#C9A227',
    skin: '#E8C4A8',
    hat: '#1A1A1A',
  },
  npc_quan_vo: {
    id: 'npc_quan_vo',
    primary: '#8B1E1E',
    secondary: '#6B2D2D',
    accent: '#D4AF37',
    skin: '#E8C4A8',
    hat: '#222222',
  },
  npc_ve_binh: {
    id: 'npc_ve_binh',
    primary: '#C62828',
    secondary: '#2E7D32',
    accent: '#E6C84A',
    skin: '#E8C4A8',
    hat: '#E6C84A',
  },
  npc_thai_giam: {
    id: 'npc_thai_giam',
    primary: '#2C3E50',
    secondary: '#3D4F5F',
    accent: '#111111',
    skin: '#E8C4A8',
    hat: '#111111',
  },
  npc_cung_nu: {
    id: 'npc_cung_nu',
    primary: '#A67C52',
    secondary: '#F5F0E6',
    accent: '#C2185B',
    skin: '#E8C4A8',
    hat: '#1A1A1A',
  },
  npc_hau: {
    id: 'npc_hau',
    primary: '#6D4C41',
    secondary: '#E8DCC8',
    accent: '#3E2723',
    skin: '#E8C4A8',
    hat: '#3E2723',
  },
  npc_tang_si: {
    id: 'npc_tang_si',
    primary: '#8D6E41',
    secondary: '#7A7A72',
    accent: '#F5F5DC',
    skin: '#E8C4A8',
    hat: '#2B2B2B',
  },
  npc_dan_ngu_than: {
    id: 'npc_dan_ngu_than',
    primary: '#3E2723',
    secondary: '#F5F0E6',
    accent: '#1A1A1A',
    skin: '#E8C4A8',
    hat: '#1A1A1A',
  },
  npc_non_la: {
    id: 'npc_non_la',
    primary: '#6D4C41',
    secondary: '#EDE6D9',
    accent: '#C4A574',
    skin: '#E8C4A8',
    hat: '#E8D5A3',
  },
  npc_tay_su: {
    id: 'npc_tay_su',
    primary: '#1B2838',
    secondary: '#F5F5F5',
    accent: '#8B0000',
    skin: '#E8C4A8',
    hat: '#2C2C2C',
  },
  npc_tourist: {
    id: 'npc_tourist',
    primary: '#2196F3',
    secondary: '#37474F',
    accent: '#FFEB3B',
    skin: '#E8C4A8',
    hat: '#FFEB3B',
  },
  npc_hoang_hau: {
    id: 'npc_hoang_hau',
    primary: '#9C1B2E',
    secondary: '#F8E7C9',
    accent: '#D4AF37',
    skin: '#E8C4A8',
    hat: '#C62828',
  },
  npc_nhac_cong: {
    id: 'npc_nhac_cong',
    primary: '#1565C0',
    secondary: '#6A1B9A',
    accent: '#111111',
    skin: '#E8C4A8',
    hat: '#111111',
  },
}

export const NPC_TYPES: Record<NpcCostumeId, NpcTypeDef> = {
  npc_vua: {
    id: 'npc_vua',
    name: 'Vua',
    height: 1.72,
    scale: 1.05,
    zones: ['wp_dai_trieu_nghi', 'wp_tu_cam'],
    walkSpeed: 0.55,
    hasHat: true,
  },
  npc_quan_van: {
    id: 'npc_quan_van',
    name: 'Quan văn',
    height: 1.68,
    scale: 1.02,
    zones: ['wp_dai_trieu_nghi', 'wp_than_dao', 'wp_mieu'],
    walkSpeed: 0.85,
    hasHat: true,
  },
  npc_quan_vo: {
    id: 'npc_quan_vo',
    name: 'Quan võ',
    height: 1.72,
    scale: 1.03,
    zones: ['wp_ngo_mon', 'wp_dai_trieu_nghi'],
    walkSpeed: 0.9,
    hasHat: true,
  },
  npc_ve_binh: {
    id: 'npc_ve_binh',
    name: 'Vệ binh',
    height: 1.7,
    scale: 1.02,
    zones: ['wp_ngo_mon', 'wp_than_dao', 'wp_dai_trieu_nghi'],
    walkSpeed: 0.95,
    hasHat: true,
  },
  npc_thai_giam: {
    id: 'npc_thai_giam',
    name: 'Thái giám',
    height: 1.6,
    scale: 0.95,
    zones: ['wp_tu_cam', 'wp_than_dao'],
    walkSpeed: 0.75,
    hasHat: true,
  },
  npc_cung_nu: {
    id: 'npc_cung_nu',
    name: 'Cung nữ',
    height: 1.55,
    scale: 0.94,
    zones: ['wp_tu_cam', 'wp_thieu_phuong'],
    walkSpeed: 0.7,
    hasHat: false,
  },
  npc_hau: {
    id: 'npc_hau',
    name: 'Người hầu',
    height: 1.6,
    scale: 0.96,
    zones: ['wp_tu_cam', 'wp_mieu', 'wp_thieu_phuong'],
    walkSpeed: 1.05,
    hasHat: true,
  },
  npc_tang_si: {
    id: 'npc_tang_si',
    name: 'Tăng sĩ',
    height: 1.65,
    scale: 1.0,
    zones: ['wp_mieu'],
    walkSpeed: 0.6,
    hasHat: true,
  },
  npc_dan_ngu_than: {
    id: 'npc_dan_ngu_than',
    name: 'Dân ngũ thân',
    height: 1.62,
    scale: 1.0,
    zones: ['wp_ngo_mon', 'wp_pho_ngoai', 'wp_than_dao'],
    walkSpeed: 0.9,
    hasHat: true,
  },
  npc_non_la: {
    id: 'npc_non_la',
    name: 'Nón lá',
    height: 1.62,
    scale: 1.0,
    zones: ['wp_ngo_mon', 'wp_pho_ngoai'],
    walkSpeed: 0.88,
    hasHat: true,
  },
  npc_tay_su: {
    id: 'npc_tay_su',
    name: 'Sứ Tây',
    height: 1.75,
    scale: 1.06,
    zones: ['wp_ngo_mon', 'wp_dai_trieu_nghi'],
    walkSpeed: 0.8,
    hasHat: true,
  },
  npc_tourist: {
    id: 'npc_tourist',
    name: 'Du khách',
    height: 1.68,
    scale: 1.0,
    zones: ['wp_ngo_mon', 'wp_than_dao', 'wp_dai_trieu_nghi', 'wp_mieu'],
    walkSpeed: 1.0,
    hasHat: true,
  },
  npc_hoang_hau: {
    id: 'npc_hoang_hau',
    name: 'Hoàng hậu',
    height: 1.58,
    scale: 0.96,
    zones: ['wp_tu_cam', 'wp_dai_trieu_nghi'],
    walkSpeed: 0.55,
    hasHat: true,
  },
  npc_nhac_cong: {
    id: 'npc_nhac_cong',
    name: 'Nhạc công',
    height: 1.62,
    scale: 0.98,
    zones: ['wp_dai_trieu_nghi', 'wp_mieu'],
    walkSpeed: 0.7,
    hasHat: true,
  },
}

export const NPC_TYPE_ORDER: NpcCostumeId[] = [
  'npc_vua',
  'npc_quan_van',
  'npc_quan_vo',
  'npc_ve_binh',
  'npc_thai_giam',
  'npc_cung_nu',
  'npc_hau',
  'npc_tang_si',
  'npc_dan_ngu_than',
  'npc_non_la',
  'npc_tay_su',
  'npc_tourist',
  'npc_hoang_hau',
  'npc_nhac_cong',
]

/** Spawn mix weights — denser common roles. */
export const SPAWN_WEIGHTS: Record<NpcCostumeId, number> = {
  npc_vua: 2,
  npc_quan_van: 18,
  npc_quan_vo: 14,
  npc_ve_binh: 40,
  npc_thai_giam: 10,
  npc_cung_nu: 16,
  npc_hau: 22,
  npc_tang_si: 12,
  npc_dan_ngu_than: 35,
  npc_non_la: 28,
  npc_tay_su: 6,
  npc_tourist: 45,
  npc_hoang_hau: 2,
  npc_nhac_cong: 8,
}
