import type { MonumentModule } from '../core/types/MonumentModule'

/**
 * Central monument registry. Orchestrator wires modules after each wave.
 * Sub-agents export modules; they do NOT edit this file unless instructed.
 */
const registry = new Map<string, MonumentModule>()

export function registerMonument(module: MonumentModule): void {
  if (registry.has(module.id)) {
    console.warn(`[registry] overwrite monument id=${module.id}`)
  }
  registry.set(module.id, module)
}

export function getMonument(id: string): MonumentModule | undefined {
  return registry.get(id)
}

export function listMonuments(): MonumentModule[] {
  return Array.from(registry.values())
}

export function clearRegistry(): void {
  registry.clear()
}
